require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/radiology_exams', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # RadiologyExam. As you add validations to RadiologyExam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      name: 'Brain scan',
      description: 'Scanned and took apart the sculp'
    }
  end

  let(:invalid_attributes) do
    {
      name: 4,
      description: nil
    }
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # RadiologyExamsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    { 'Content-Type' => 'application/json' }
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      RadiologyExam.create! valid_attributes
      get radiology_exams_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      radiology_exam = RadiologyExam.create! valid_attributes
      get radiology_exam_url(radiology_exam), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new RadiologyExam' do
        expect do
          post radiology_exams_url,
               params: { radiology_exam: valid_attributes }, headers: valid_headers, as: :json
        end.to change(RadiologyExam, :count).by(1)
      end

      it 'renders a JSON response with the new radiology_exam' do
        post radiology_exams_url,
             params: { radiology_exam: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new RadiologyExam' do
        expect do
          post radiology_exams_url,
               params: { radiology_exam: invalid_attributes }, as: :json
        end.to change(RadiologyExam, :count).by(0)
      end

      it 'renders a JSON response with errors for the new radiology_exam' do
        post radiology_exams_url,
             params: { radiology_exam: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {
          name: 'Back scan',
          description: 'Scanned and took apart the spine'
        }
      end

      it 'updates the requested radiology_exam' do
        radiology_exam = RadiologyExam.create! valid_attributes
        patch radiology_exam_url(radiology_exam),
              params: { radiology_exam: new_attributes }, headers: valid_headers, as: :json
        radiology_exam.reload
        expect(radiology_exam.name).to eq('Back scan')
      end

      it 'renders a JSON response with the radiology_exam' do
        radiology_exam = RadiologyExam.create! valid_attributes
        patch radiology_exam_url(radiology_exam),
              params: { radiology_exam: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the radiology_exam' do
        radiology_exam = RadiologyExam.create! valid_attributes
        patch radiology_exam_url(radiology_exam),
              params: { radiology_exam: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested radiology_exam' do
      radiology_exam = RadiologyExam.create! valid_attributes
      expect do
        delete radiology_exam_url(radiology_exam), headers: valid_headers, as: :json
      end.to change(RadiologyExam, :count).by(-1)
    end
  end
end
