require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe '/visits', type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Visit. As you add validations to Visit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    # skip('Add a hash of attributes valid for your model')
    {:visit_no=>'2', :visit_owner=>'Caitylyn', :visit_date=>'2023-01-23', :visit_type=>'review', :visit_category=>'insurance', :speciality=>'cardiology', :member_no=>'2A5R2', :service=>'Consultation'}
  end

  let(:invalid_attributes) do
    {:visit_no=>'', :visit_owner=>'', :visit_date=>'2023-01', :visit_type=>'', :visit_category=>'', :speciality=>'', :member_no=>'', :service=>''}
  end

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # VisitsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) do
    {"Content-Type" => "application/json"}
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      Visit.create! valid_attributes
      get visits_path, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      visit = Visit.create! valid_attributes
      get visit_path(visit), as: :json
      expect(response).to be_successful
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new Visit' do
        expect do
          post visits_path,
               params: { visit: valid_attributes }, headers: valid_headers, as: :json
        end.to change(Visit, :count).by(1)
      end

      it 'renders a JSON response with the new visit' do
        post visits_path,
             params: { visit: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new Visit' do
        expect do
          post visits_path,
               params: { visit: invalid_attributes }, as: :json
        end.to change(Visit, :count).by(0)
      end

      it 'renders a JSON response with errors for the new visit' do
        post visits_path,
             params: { visit: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        {:visit_no=>'2', :visit_owner=>'Caitylyn', :visit_date=>'2023-01-23', :visit_type=>'review', :visit_category=>'insurance', :speciality=>'cardiology', :member_no=>'2A5R2', :service=>'Treatment'}
      end

      it 'updates the requested visit' do
        visit = Visit.create! valid_attributes
        patch visit_url(visit),
              params: { visit: new_attributes }, headers: valid_headers, as: :json
        visit.reload
        {:visit_no=>'2', :visit_owner=>'Caitylyn', :visit_date=>'2023-01-23', :visit_type=>'review', :visit_category=>'insurance', :speciality=>'cardiology', :member_no=>'2A5R2', :service=>'Treatment'}
      end

      it 'renders a JSON response with the visit' do
        visit = Visit.create! valid_attributes
        patch visit_url(visit),
              params: { visit: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end

    context 'with invalid parameters' do
      it 'renders a JSON response with errors for the visit' do
        visit = Visit.create! valid_attributes
        patch visit_url(visit),
              params: { visit: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to match(a_string_including('application/json'))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested visit' do
      visit = Visit.create! valid_attributes
      expect do
        delete visit_path(visit), headers: valid_headers, as: :json
      end.to change(Visit, :count).by(-1)
    end
  end
end
